// Generated from ja2-stracciatella assets/externalized/mercs-profile-info.json
// at commit dcc20b3c24b3e49ccd16e9d4ae87dcd20b9e51ea.
// Input SHA-256: d51e1f99f58ad3b7e6b03247122807ba686ab7741182332955aab42f7f25cf0a.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StockProfileType {
    Npc,
    Rpc,
}

#[derive(Debug, Clone, Copy)]
pub struct StockProfile {
    pub canonical_name: &'static str,
    pub profile_type: StockProfileType,
}

pub fn stock_npc_or_rpc(id: u8) -> Option<StockProfile> {
    let (canonical_name, profile_type) = match id {
        57 => ("MIGUEL", StockProfileType::Rpc),
        58 => ("CARLOS", StockProfileType::Rpc),
        59 => ("IRA", StockProfileType::Rpc),
        60 => ("DIMITRI", StockProfileType::Rpc),
        61 => ("DEVIN", StockProfileType::Rpc),
        62 => ("ROBOT", StockProfileType::Rpc),
        63 => ("HAMOUS", StockProfileType::Rpc),
        64 => ("SLAY", StockProfileType::Rpc),
        65 => ("RPC65", StockProfileType::Rpc),
        66 => ("DYNAMO", StockProfileType::Rpc),
        67 => ("SHANK", StockProfileType::Rpc),
        68 => ("IGGY", StockProfileType::Rpc),
        69 => ("VINCE", StockProfileType::Rpc),
        70 => ("CONRAD", StockProfileType::Rpc),
        71 => ("RPC71", StockProfileType::Rpc),
        72 => ("MADDOG", StockProfileType::Rpc),
        73 => ("DARREL", StockProfileType::Rpc),
        74 => ("PERKO", StockProfileType::Rpc),
        75 => ("QUEEN", StockProfileType::Npc),
        76 => ("AUNTIE", StockProfileType::Npc),
        77 => ("ENRICO", StockProfileType::Npc),
        78 => ("CARMEN", StockProfileType::Npc),
        79 => ("JOE", StockProfileType::Npc),
        80 => ("STEVE", StockProfileType::Npc),
        81 => ("RAT", StockProfileType::Npc),
        82 => ("ANNIE", StockProfileType::Npc),
        83 => ("CHRIS", StockProfileType::Npc),
        84 => ("BOB", StockProfileType::Npc),
        85 => ("BRENDA", StockProfileType::Npc),
        86 => ("KINGPIN", StockProfileType::Npc),
        87 => ("DARREN", StockProfileType::Npc),
        88 => ("MARIA", StockProfileType::Npc),
        89 => ("ANGEL", StockProfileType::Npc),
        90 => ("JOEY", StockProfileType::Npc),
        91 => ("TONY", StockProfileType::Npc),
        92 => ("FRANK", StockProfileType::Npc),
        93 => ("SPIKE", StockProfileType::Npc),
        94 => ("DAMON", StockProfileType::Npc),
        95 => ("KYLE", StockProfileType::Npc),
        96 => ("MICKY", StockProfileType::Npc),
        97 => ("SKYRIDER", StockProfileType::Npc),
        98 => ("PABLO", StockProfileType::Npc),
        99 => ("SAL", StockProfileType::Npc),
        100 => ("FATHER", StockProfileType::Npc),
        101 => ("FATIMA", StockProfileType::Npc),
        102 => ("WARDEN", StockProfileType::Npc),
        103 => ("GORDON", StockProfileType::Npc),
        104 => ("GABBY", StockProfileType::Npc),
        105 => ("ERNEST", StockProfileType::Npc),
        106 => ("FRED", StockProfileType::Npc),
        107 => ("MADAME", StockProfileType::Npc),
        108 => ("YANNI", StockProfileType::Npc),
        109 => ("MARTHA", StockProfileType::Npc),
        110 => ("TIFFANY", StockProfileType::Npc),
        111 => ("T_REX", StockProfileType::Npc),
        112 => ("DRUGGIST", StockProfileType::Npc),
        113 => ("JAKE", StockProfileType::Npc),
        114 => ("PACOS", StockProfileType::Npc),
        115 => ("GERARD", StockProfileType::Npc),
        116 => ("SKIPPER", StockProfileType::Npc),
        117 => ("HANS", StockProfileType::Npc),
        118 => ("JOHN", StockProfileType::Npc),
        119 => ("MARY", StockProfileType::Npc),
        120 => ("GENERAL", StockProfileType::Npc),
        121 => ("SERGEANT", StockProfileType::Npc),
        122 => ("ARMAND", StockProfileType::Npc),
        123 => ("LORA", StockProfileType::Npc),
        124 => ("FRANZ", StockProfileType::Npc),
        125 => ("HOWARD", StockProfileType::Npc),
        126 => ("SAM", StockProfileType::Npc),
        127 => ("ELDIN", StockProfileType::Npc),
        128 => ("ARNIE", StockProfileType::Npc),
        129 => ("TINA", StockProfileType::Npc),
        130 => ("FREDO", StockProfileType::Npc),
        131 => ("WALTER", StockProfileType::Npc),
        132 => ("JENNY", StockProfileType::Npc),
        133 => ("BILLY", StockProfileType::Npc),
        134 => ("BREWSTER", StockProfileType::Npc),
        135 => ("ELLIOT", StockProfileType::Npc),
        136 => ("DEREK", StockProfileType::Npc),
        137 => ("OLIVER", StockProfileType::Npc),
        138 => ("WALDO", StockProfileType::Npc),
        139 => ("DOREEN", StockProfileType::Npc),
        140 => ("JIM", StockProfileType::Npc),
        141 => ("JACK", StockProfileType::Npc),
        142 => ("OLAF", StockProfileType::Npc),
        143 => ("RAY", StockProfileType::Npc),
        144 => ("OLGA", StockProfileType::Npc),
        145 => ("TYRONE", StockProfileType::Npc),
        146 => ("MADLAB", StockProfileType::Npc),
        147 => ("KEITH", StockProfileType::Npc),
        148 => ("MATT", StockProfileType::Npc),
        149 => ("MIKE", StockProfileType::Npc),
        150 => ("DARYL", StockProfileType::Npc),
        151 => ("HERVE", StockProfileType::Npc),
        152 => ("PETER", StockProfileType::Npc),
        153 => ("ALBERTO", StockProfileType::Npc),
        154 => ("CARLO", StockProfileType::Npc),
        155 => ("MANNY", StockProfileType::Npc),
        156 => ("OSWALD", StockProfileType::Npc),
        157 => ("CALVIN", StockProfileType::Npc),
        158 => ("CARL", StockProfileType::Npc),
        159 => ("SPECK", StockProfileType::Npc),
        _ => return None,
    };
    Some(StockProfile {
        canonical_name,
        profile_type,
    })
}
